# Generated by Django 4.2.1 on 2023-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(verbose_name="작성일"),
        ),
    ]
